name: "Ohmigon"
description: "A add-on to control Ohmigo-USB from Home Assistant"
version: "0.0.1"
url: https://github.com/nsg/ohmigon
slug: "ohmigon"
init: false
startup: application

full_access: true
#uart: true
#usb: true
#devices:
#  - /dev/ttyUSB0

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  device: null
  startup_outdoor_temperature: 10
  mqtt_topic: ohmigon
schema:
  device: device(subsystem=tty)
  startup_outdoor_temperature: int
  mqtt_topic: str
services:
  - mqtt:need
